447 show buttons in workbatch according to configuration
commonlims/commonlims pull request #204
Opened 2020-10-14 13:22 UTC by GitEdvard

Purpose:
Show buttons in a workbatch view according to an configuration provided by the api. 

Scope:
This is an implementation in the UI only. The corresponding endpoints /workbatch-details and /actions is not yet implemented in the backend. Furthermore, since a workbatch page is not yet in place, I started with one here and called it "example workbatch". This page only handles buttons, nothing else. 

Implementation:
I use the general actions creators in shared.js to create actions for the button clicked events. And also extended the existing action/reducers for workbatch details. 

Note:
In order to get this working in UI, you have to comment out/comment in the last lines in workBatchDetails.js ("hook up with the backend"...)

2020-10-29 11:55 UTC, mariya requested changes
The code looks fine, but I have some questions/comments about naming. Is the intention that ExampleWorkbatchContainer will at some point be edited to include the real implementation? If so, I think it is better to just name it WorkbatchContainer directly and just add TODO comments where applicable. If the plan is to replace ExampleWorkbatchContainer entirely in the future, then perhaps DummyWorkbatchContainer is a clearer name for something intended to be thrown away?

2020-10-29 12:09 UTC, GitEdvard commented
Yes, my intention was that ExampleWorkbatch would be used in future. So I'll rename it. Thanks for the comment.

2020-10-30 09:29 UTC, GitEdvard commented
I discovered that there are already an existing workbatch details container, and unfortunately this cannot be shown as the current state of the clims. Therefore I renamed my view to workBatchDetailsWaitingToBeMerged. (It will now show up next to the original view which is good). I also split up the code into a Container and Presentational class, in a similar manner as other views.

2020-11-04 08:13 UTC, mariya approved these changes
This looks good to me, feel free to merge!

2020-11-04 09:16 UTC, merged