clims-289, Fix MultiFormatFile taking path as input
commonlims/commonlims pull request #90
Opened 2019-11-22 09:35 UTC by GitEdvard

A similar class was defined within the sample sub validation module. I
wanted a more central place for it, since it now was used at two
locations.

2019-11-22 12:37 UTC, johandahlberg commented
I'm not sure we actually need two classes for this. Wouldn't it be better to do a single class, and then have several factory methods to initiate it? This could either take the form of a `MultiFormatFileFactor` class, or which I think is a little bit more pythonic, just two functions, one `from_organization_file(...)` and one `from_path(...)`. What do you think?

2019-11-22 13:05 UTC, GitEdvard commented
I have now added a wrapper class for MultiFormatFile, having factory methods from_path and from_organziation_file. I'm not really sure this is what you had in mind though. I was reluctant to merge it in one single class, because it would require an if-else clause in each method, and I didn't like that. I may still change my mind if you insist, so please speak your opinion!

2019-11-25 12:04 UTC, GitEdvard commented
Now, there is a refactored version of the MultiFormatFile. I have tried to avoid having multiple calls to xl. open_workbook spread out over two classes. Instead I have created internal classes of type FileContext, which deal with the temp file for organization files.

Note that tests in the snpseq repo will fail until the corresponding PR there will be merged.

2019-11-25 12:33 UTC, johandahlberg requested changes

2019-11-25 12:33 UTC, johandahlberg commented on src/clims/models/file.py
> +        return MultiFormatFile(file_context=file_context)
I think these two should be made `staticmethod` rather than `classmethod`.

2019-11-25 12:46 UTC, merged